##PMM

pmm_server: 
pmm_user: foouser
pmm_passwd: foopassword
pmm_version: "{{ global_pmm_version | default('1.17.1') }}"
pmm_install_version: "{{ pmm_version }}"
change_ssh_default_port: 22

##NODE_EXPORTER

exporter_user: node_exporter
default_user_password: gdfcj
exporter_user_manage: true
exporter_group: node_exporter
exporter_group_manage: true
node_exporter_version: 1.4.0
node_exporter_dir: "/opt/prometheus/exporters"
#node_exporter_dist_dir: "{{ node_exporter_dir }}/dist"
node_exporter_service_mgr: "{{ ansible_service_mgr }}"
node_exporter_service_packages: []
node_exporter_ansible_packages:
  - "{{ 'libselinux-python' if ansible_facts['python']['version']['major'] == 2 else 'python3-libselinux' }}"

node_exporter_platform_suffix: "linux-amd64"
node_exporter_signature: "node_exporter-{{ node_exporter_version }}.{{ node_exporter_platform_suffix }}"
node_exporter_dist_dir: "/usr/src/{{ node_exporter_signature }}"
node_exporter_tarball_url: "https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/{{ node_exporter_signature }}.tar.gz"
node_exporter_program: "{{ node_exporter_dir }}/node_exporter"
node_exporter_home: "/var/lib/node_exporter"
node_exporter_home_manage: true

node_exporter_config_file: /etc/default/node_exporter
node_exporter_pid_path: "/var/run"
node_exporter_log_path: "/var/log/node_exporter"

node_exporter_service_manage: true
node_exporter_service_enable: true
node_exporter_service_state: started
node_exporter_service_notify: true
node_exporter_port: 9100

##NGINX_EXPORTER

nginx_exporter_version: "0.8.0"
nginx_exporter_tarball_checksum: "sha256:fce51ce62650186f9f4cb3ff13fa4b36ffc2980058a63bccdb471c929c078e50"
nginx_exporter_platform_suffix: "linux-amd64"

nginx_exporter_signature: "nginx-prometheus-exporter-{{ nginx_exporter_version }}-{{ nginx_exporter_platform_suffix }}"
nginx_exporter_dist_dir: "/usr/src/{{ nginx_exporter_signature }}"
nginx_exporter_tarball_url: "https://github.com/nginxinc/nginx-prometheus-exporter/releases/download/v{{ nginx_exporter_version }}/{{ nginx_exporter_signature }}.tar.gz"
nginx_exporter_program: "{{ prometheus_exporter_dir }}/nginx_exporter"
nginx_exporter_home: "/var/lib/nginx_exporter"
nginx_exporter_home_manage: true
nginx_exporter_options:
  - '-nginx.scrape-uri http://localhost:8080/nginx_status'

nginx_exporter_config_file: /etc/default/nginx_exporter
nginx_exporter_pid_path: "/var/run"
nginx_exporter_log_path: "/var/log/nginx_exporter"

nginx_exporter_service_manage: true
nginx_exporter_service_enable: true
nginx_exporter_service_state: started
nginx_exporter_service_notify: true
nginx_exporter_port: 9113

##POSTGRES_EXPORTER

postgres_exporter_user: postgres
postgres_exporter_group: postgres
postgres_exporter_version: "0.11.1"
postgres_exporter_tarball_checksum: "sha256:ec27e2a52b764c4313076ea6db335607cc40fb8a503dcb74d9517dc8baf049f0"
postgres_exporter_platform_suffix: "linux-amd64"

postgres_exporter_signature: "postgres_exporter-{{ postgres_exporter_version }}.{{ postgres_exporter_platform_suffix }}"
postgres_exporter_dist_dir: "/usr/src/{{ postgres_exporter_signature }}"
postgres_exporter_tarball_url: "https://github.com/prometheus-community/postgres_exporter/releases/download/v{{ postgres_exporter_version }}/{{ postgres_exporter_signature }}.tar.gz"
postgres_exporter_program: "{{ prometheus_exporter_dir }}/postgres_exporter"
postgres_exporter_home: "/var/lib/postgres_exporter"
postgres_exporter_home_manage: true
postgres_exporter_options:
  - 'DATA_SOURCE_NAME="user=postgres host=/var/run/postgresql/ sslmode=disable" postgres_exporter'

postgres_exporter_config_file: /etc/default/postgres_exporter
postgres_exporter_pid_path: "/var/run"
postgres_exporter_log_path: "/var/log/postgres_exporter"

postgres_exporter_service_manage: true
postgres_exporter_service_enable: true
postgres_exporter_service_state: started
postgres_exporter_service_notify: true
postgres_exporter_port: 9187

##REDIS_EXPORTER

redis_exporter_version: 1.3.1
redis_exporter_release_system: linux-amd64
redis_exporter_release_name: "redis_exporter-v{{ redis_exporter_version }}.{{ redis_exporter_release_system }}"
redis_exporter_package: "{{ redis_exporter_release_name}}.tar.gz"
redis_exporter_url: "https://github.com/oliver006/redis_exporter/releases/download/v{{ redis_exporter_version }}/{{ redis_exporter_package }}"
redis_exporter_download_path: /usr/src
redis_exporter_package_path: "{{ redis_exporter_download_path }}/{{ redis_exporter_package }}"
redis_exporter_src_bin: "{{ redis_exporter_download_path }}/{{ redis_exporter_release_name }}/redis_exporter"
# Redis Exporter 0.x has a different packaging
#redis_exporter_src_bin: "{{ redis_exporter_download_path }}/redis_exporter"

# Set true to force the download and installation of the binary
redis_exporter_force_reinstall: false

redis_exporter_private_tmp: true
redis_exporter_service_enabled: True
redis_exporter_service_state: started
redis_exporter_log_path: /var/log/redis_exporter
redis_exporter_log_file: redis_exporter.log
redis_exporter_log_output: journal
redis_exporter_root_path: /opt/redis_exporter
redis_exporter_bin_path: "{{ redis_exporter_root_path }}/bin"
redis_exporter_port: 9121
redis_exporter_ip: 0.0.0.0
redis_exporter_debug: false
redis_exporter_log_format: txt #(txt | json)
redis_exporter_check_keys: ""
redis_exporter_redis_addr: redis://localhost:6379
redis_exporter_redis_password: ""
redis_exporter_redis_alias: redis_{{ ansible_nodename }}
redis_exporter_redis_namespace: redis
redis_exporter_web_telemetry_path: metrics
redis_exporter_options:
  - "{{ redis_exporter_debug | ternary('debug','') }}"
  - "log-format {{ redis_exporter_log_format }}"
  - "{{ redis_exporter_check_keys | ternary('check-keys ' + redis_exporter_check_keys, '') }}"
  - "redis.addr {{ redis_exporter_redis_addr }}"
  - "{{ redis_exporter_redis_password | ternary('redis.password ' + redis_exporter_redis_password, '') }}"
  - "namespace {{ redis_exporter_redis_namespace }}"
  - "web.listen-address {{ redis_exporter_ip }}:{{ redis_exporter_port }}"
  - "web.telemetry-path /{{ redis_exporter_web_telemetry_path }}"
#  redis.alias only for 0.x version https://github.com/oliver006/redis_exporter/pull/256
#  - "redis.alias {{ redis_exporter_redis_alias }}"

##PUMA_EXPORTER

puma_exporter_version: 0.1.0
puma_exporter_release_system: linux-amd64
puma_exporter_private_tmp: true
puma_exporter_service_enabled: True
puma_exporter_service_state: started
puma_exporter_log_path: /var/log/puma_exporter
puma_exporter_log_file: puma_exporter.log
puma_exporter_log_output: journal
puma_exporter_root_path: /opt/puma_exporter
puma_exporter_bin_path: "{{ puma_exporter_root_path }}/bin"
puma_exporter_port: 9394
puma_exporter_ip: 0.0.0.0
puma_exporter_debug: false
puma_exporter_log_format: txt #(txt | json)
puma_exporter_check_keys: ""
puma_exporter_puma_addr: puma://localhost:6379
puma_exporter_puma_password: ""
puma_exporter_puma_alias: puma_{{ ansible_nodename }}
puma_exporter_puma_namespace: puma
puma_exporter_web_telemetry_path: metrics
puma_exporter_options:
  - "{{ puma_exporter_debug | ternary('debug','') }}"
  - "log-format {{ puma_exporter_log_format }}"
  - "{{ puma_exporter_check_keys | ternary('check-keys ' + puma_exporter_check_keys, '') }}"
  - "puma.addr {{ puma_exporter_puma_addr }}"
  - "{{ puma_exporter_puma_password | ternary('puma.password ' + puma_exporter_puma_password, '') }}"
  - "namespace {{ puma_exporter_puma_namespace }}"
  - "web.listen-address {{ puma_exporter_ip }}:{{ puma_exporter_port }}"
  - "web.telemetry-path /{{ puma_exporter_web_telemetry_path }}"

##SIDEKIQ_EXPORTER

sidekiq_exporter_version: 0.1.17
sidekiq_exporter_release_system: linux-amd64
sidekiq_exporter_private_tmp: true
sidekiq_exporter_service_enabled: True
sidekiq_exporter_service_state: started
sidekiq_exporter_log_path: /var/log/sidekiq_exporter
sidekiq_exporter_log_file: sidekiq_exporter.log
sidekiq_exporter_log_output: journal
sidekiq_exporter_root_path: /opt/sidekiq_exporter
sidekiq_exporter_bin_path: "{{ sidekiq_exporter_root_path }}/bin"
sidekiq_exporter_port: 9293
sidekiq_exporter_ip: 0.0.0.0
sidekiq_exporter_debug: false
sidekiq_exporter_log_format: txt #(txt | json)
sidekiq_exporter_check_keys: ""
sidekiq_exporter_sidekiq_password: ""
sidekiq_exporter_sidekiq_alias: sidekiq_{{ ansible_nodename }}
sidekiq_exporter_sidekiq_namespace: sidekiq
sidekiq_exporter_web_telemetry_path: metrics
sidekiq_exporter_options:
  - "{{ sidekiq_exporter_debug | ternary('debug','') }}"
  - "log-format {{ sidekiq_exporter_log_format }}"
  - "{{ sidekiq_exporter_check_keys | ternary('check-keys ' + sidekiq_exporter_check_keys, '') }}"
  - "sidekiq.addr {{ sidekiq_exporter_sidekiq_addr }}"
  - "{{ sidekiq_exporter_sidekiq_password | ternary('sidekiq.password ' + sidekiq_exporter_sidekiq_password, '') }}"
  - "namespace {{ sidekiq_exporter_sidekiq_namespace }}"
  - "web.listen-address {{ sidekiq_exporter_ip }}:{{ sidekiq_exporter_port }}"
  - "web.telemetry-path /{{ sidekiq_exporter_web_telemetry_path }}"


