- name: restart postgres_exporter
  become: true
  become_user: "{{ postgres_exporter_user }}"
  service:
    name: postgres_exporter
    state: "{{ (postgres_exporter_service_state != 'stopped') | ternary('restarted', 'stopped') }}"
    use: "{{ ansible_service_mgr }}"
  when: postgres_exporter_service_notify and (
    _postgres_exporter_service_state is not defined or
    not ( _postgres_exporter_service_state is changed ))

- name: reload systemd daemon
  become: true
  become_user: root
  systemd:
    daemon-reload: true
