- hosts: all
  gather_facts: true
  roles:
    - create_user
    - install_pmm-agent
    - system_config
    - node_exporter
    - nginx_exporter
    - redis_exporter
    - puma_exporter
    - sidekiq_exporter
    - postgres_exporter
