---
- name: REDIS_EXPORTER | Copy Daemon script
  become: true
  become_user: root
  template:
    src: redis_exporter.service.j2
    dest: /etc/systemd/system/redis_exporter.service
    mode: 0644
  notify: restart redis_exporter
